### ISSUE TITLE
Pulse counter in smart-MAIC D105 not showing in Home assistant

### ISSUE THREAD

**Issue by TonioClos** [krasnoukhov/homeassistant-smart-maic#14] opened 2024-04-08 18:03 UTC
Hello!
I´m using your integration with home assistant and everything was working fine until I tried to add the pulse counter option in a Smart MAIC D105. After adding it, it´s not showing in Home Assistant interface and I don´t have any option to add it.
The product it´s brand new, firmware was updated and while sniffing the MQTT messages, it´s showing how the Ch1 value is correctly send.
I would love a helping hand in here, because not finding much about people not getting the data show in their HA.
Thank you so much beforehand.
Have a nice day!

**Comment by krasnoukhov** [comment] 2024-04-13 11:54
Hi, this seems like a duplicate of #11

**Closed by krasnoukhov** 2024-04-13 11:54 UTC
